### ISSUE TITLE
Problem with Drop-down terminal

### ISSUE THREAD

**Issue by elandx** [blueyed/awesome-cyclefocus#10]
Hi,
thanks for cyclefocus!  
It works as expected with one exception.  I use quake-like drop-dwon terminal (http://awesome.naquadah.org/wiki/Drop-down_terminal#Another_solution) and it remains open hiding other windows then I cycle  through all windows with Mod4-Tab.  Thanks in advance.

**Comment by blueyed** [comment]
@elandx 
I have a huge rewrite / improvement locally, which might help with that: it sets the currently selected window `ontop`.

Since the changes are huge, I've planned to clean them up etc.. let me know if you feel adventurous to try out a non-master branch and I could push what I have (but not in the next days).

**Comment by elandx** [comment]
Thank you for such a quick response. Of course, I'm willing to try an experimental version. Good luck :)

**Comment by blueyed** [comment]
Here it finally is: #14.

**Comment by blueyed** [comment]
Assuming to be fixed, please re-open and report back otherwise.
