### ISSUE TITLE
alt + tab resets fullscreen mode

### ISSUE THREAD

**Issue by D1mon** [blueyed/awesome-cyclefocus#26]
alt + tab resets fullscreen mode and does not get back up.
Reproduce the problem:
I opened the video player in full-screen mode and pressed alt + tab.

**Comment by drgibbon** [comment]
Awesome 4.2, can confirm that behaviour here also.

**Comment by blueyed** [comment]
This is because setting `ontop = true` for the currently selected client.  See https://github.com/awesomeWM/awesome/issues/667.

Please try https://github.com/blueyed/awesome-cyclefocus/pull/27.

An unsolved issue there still is that with a fullscreen and ontop client on a tiled layout, the fullscreen client will not be visible when selected.
A solution might be to set "ontop" then - ensuring basically that it becomes visible, but I am not sure if that's good?!

**Comment by blueyed** [comment]
Came up with https://github.com/awesomeWM/awesome/pull/2512 for awesome itself - would be nice to have this in the next release, but a fix for this (#27) is still valid, of course.

The problem that a selected client might not be visible in the end is another issue though, and not really the responsibility of awesome-cyclefocus I guess.  Still interested about ideas, of course.

**Comment by drgibbon** [comment]
After a pull to 127a082f25cd9237e129e6547cd2fa83bd749afb the problem seems to be fixed, thanks!
